### ISSUE TITLE
Numerical preference item does not work when input is cleared

### ISSUE THREAD

**Issue by jcc37** [googleinterns/guide-doge#38]
The input field in `preference-item` component disappears and never appears again until refreshing page when the value is cleared.

**Comment by 64json** [comment]
good catch! In addition to that, the a11y components would keep getting rerendered while typing numbers, so we should consider only updating when pressing <kbd>ENTER</kbd> or losing focus from `<input>`.

**Comment by jcc37** [comment]
@64json Isn't that a feature? My workaround is to pipe the preference subject to throttle to prevent the rapid change of the value.

**Comment by 64json** [comment]
> @64json Isn't that a feature? My workaround is to pipe the preference subject to throttle to prevent the rapid change of the value.

That sounds better.

**Comment by 64json** [comment]
Closed by #42
